version: '3.7'
services:
  mikrotik-acl:
    image: mikrotik-acl:latest
    container_name: mikrotik-acl
    hostname: mikrotik-acl
    depends_on:
      - mongo
    ports:
      - 3333:3333
    volumes:
      - ./config.yml:/app/config.yml
      - ./templates:/app/templates
  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    volumes:
      - ./data:/data/db