version: '3.7'
services:
  mikrotik-acl:
    image: ogi4i/mikrotik-provisioning:latest
    container_name: mikrotik-provisioning
    hostname: mikrotik-provisioning
    depends_on:
      - mongo
    ports:
      - 3333:3333
    volumes:
      - ./config.yml:/app/config.yml
  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    volumes:
      - ./data:/data/db